accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('', dashboard_view, name="dashboard"),
    path('login', login_view, name="login"),
    path('logout', logout_view, name="logout"),
    path('signup', signup_view, name="signup"),
    path('dashboard', dashboard_view, name="dashboard"),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
]

course/urls.py
from django.urls import path
from course.views import *

app_name = 'course'

urlpatterns = [
    path('<int:category_id>/course/<int:course_id>', course_view, name="course-single"),
    path('<int:pid>', category_single, name="single"),
    path('', categories_view, name="categories"),

]

farakooshan_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from website.views import change_lang

urlpatterns = [
    
    path('change_lang', change_lang, name='change_lang'),

]
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('category/', include('course.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

urlpatterns = [
    path('', home_view),
    path('contact', home_view),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from translated_fields import TranslatedField
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = TranslatedField(models.CharField(max_length=255))
    content = TranslatedField(RichTextField(blank=True, null=True))
    # tag 
    category = models.ManyToManyField(Category)
    # course
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return "{} - {}".format(self.title, self.id)
    

course/models.py
from django.db import models
from django.core.validators import FileExtensionValidator 
from translated_fields import TranslatedField
from ckeditor.fields import RichTextField
# Create your models here.
class Category(models.Model):
    name = TranslatedField(models.CharField(max_length=255))
    content = TranslatedField(RichTextField(blank=True, null=True))
    
    # image
    def __str__(self):
        return self.name
    
class Course(models.Model):
    image = models.ImageField(upload_to='course/', default='course/default.jpg')
    title = TranslatedField(models.CharField(max_length=255))
    price = TranslatedField(models.IntegerField(default=0))
    video = models.FileField(upload_to='course/',null=True, blank=True,validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])
    # tag 
    category = models.ManyToManyField(Category)
    # post
    content = TranslatedField(RichTextField(blank=True, null=True))
    description = TranslatedField(RichTextField(blank=True, null=True))
    objectives = TranslatedField(RichTextField(blank=True, null=True))
    whoshouldattend = TranslatedField(RichTextField(blank=True, null=True))
    cpdunit = TranslatedField(RichTextField(blank=True, null=True))
    location = TranslatedField(models.CharField(max_length=255))

    status = models.BooleanField(default=False)
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    updated_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return "{} - {}".format(self.title, self.id)

website/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

accounts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.

def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return render(request, 'accounts/dashboard.html')
        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/')

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
        form = UserCreationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/')

def dashboard_view(request):
    if request.user.is_authenticated:
        return render(request, 'accounts/dashboard.html')
    else:
        return redirect('/')

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post
# Create your views here.

def blog_view(request):
    posts = Post.objects.filter(status=1)
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

def blog_single(request, pid):
    post = get_object_or_404(Post,pk=pid,status=1)
    context = {'post': post}
    return render(request, 'blog/blog-single.html', context)

course/views.py
from django.shortcuts import render, get_object_or_404
from course.models import Category, Course
# Create your views here.

def categories_view(request):
    categories = Category.objects.all()
    context = {'categories': categories}
    return render(request, 'category/category-home.html', context)

def category_single(request, pid):
    courses = get_object_or_404(Category,pk=pid).course_set.all()
    category = get_object_or_404(Category,pk=pid)
    context = {'courses': courses, 'category_pid': pid, 'category': category}
    return render(request, 'category/category-single.html', context)

def course_view(request, category_id, course_id):
    course = get_object_or_404(Course,pk=course_id)
    context = {'course': course}
    return render(request, 'course/course.html', context)

website/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from course.models import Category
from django.utils.translation import activate
# Create your views here.

def home_view(request):
    categories = Category.objects.all()
    context = {"categories": categories}
    # activate('en')
    return render(request, 'website/index.html', context)

def about_view(request):
    return render(request, 'website/about.html')

def contact_view(request):
    return render(request, 'website/contact.html')

def change_lang(request):
    activate(request.GET.get('lang'))
    return redirect(request.GET.get('next'))

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="bg-[#f1f1f1] p-5">
    <div class="px-24 py-10 w-3/4 justify-center m-auto bg-white mt-4 mb-5">
        <h1 class="text-3xl font-bold text-[#444444]">My Account</h1>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-40">
            <div class="justify-center">
                <h1 class="text-xl m-auto text-center p-10 font-semibold text-[#444444]">Login</h1>
                <form method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    <div>
                        <label class="block font-semibold" for="name">Username</label>
                        <input name="username"
                            class="w-full shadow-inner bg-gray-100 rounded-sm placeholder-black text-xl p-1 border-none block mt-1"
                            id="name" type="text" name="name" required="required" autofocus="autofocus">
                    </div>

                    <div class="mt-4">
                        <label class="block font-semibold" for="password">Password</label>
                        <input name="password"
                            class="w-full shadow-inner bg-gray-100 rounded-sm placeholder-black text-xl p-1 border-none block mt-1"
                            id="password" type="password" name="password" required="required"
                            autocomplete="new-password">
                    </div>

                    <div class="items-center justify-between mt-8">
                        <a href="#" class="pb-5 mb-5 text-[#444444]">Forot your password?</a>
                        <button type="submit"
                            class="login-button w-full flex items-center justify-center border border-transparent text-base font-medium rounded-md text-white bg-[#005797] hover:bg-[#000831] md:py-3 md:text-sm md:px-1">
                            Log In
                        </button>
                    </div>
                </form>
            </div>

            <div>
                <h1 class="text-xl m-auto text-center p-10 font-semibold text-[#444444]">Register</h1>
                <form method="post" action="{% url 'accounts:signup' %}">
                    {% csrf_token %}
                    <div>
                        <label class="block font-semibold" for="name">Username</label>
                        <input
                            class="w-full shadow-inner bg-gray-100 rounded-sm placeholder-black text-xl p-1 border-none block mt-1"
                             type="text" name="username" required="required" autofocus="autofocus">
                    </div>

                    <div class="mt-4">
                        <label class="block font-semibold" for="password">Password</label>
                        <input
                            class="w-full shadow-inner bg-gray-100 rounded-sm placeholder-black text-xl p-1 border-none block mt-1"
                            type="password" name="password1" required="required"
                            autocomplete="new-password">
                    </div>

                    <div class="mt-4">
                        <label class="block font-semibold" for="password">Confirm Password</label>
                        <input
                            class="w-full shadow-inner bg-gray-100 rounded-sm placeholder-black text-xl p-1 border-none block mt-1"
                            type="password" name="password2" required="required"
                            autocomplete="new-password">
                    </div>

                    <div class="flex items-center justify-between mt-8">
                        <button type="submit"
                            class="w-full flex items-center justify-center p-1 border border-transparent text-base font-medium rounded-md text-white bg-[#005797] hover:bg-[#000831] md:p-3 md:text-sm ">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'CSS/styles.css' %}">
    
    {% if LANGUAGE_CODE == 'fa' %}
    <link rel="stylesheet" href="{% static 'CSS/rtl.css' %}">
    {% endif %}
    <link href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap"rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js"
        integrity="sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.min.css" rel="stylesheet">
    <title>{% translate 'Farakooshan' %}</title>
</head>

<body class="font-body bg-[#f1f1f1]">

    <!-- navbar section -->
    <section class="bg-white navbarsection">
        <div class="navbarsection">
            
            <div class="p-1 border-b-2 lg:flex flex-col md:flex-row md:items-center text-center md:space-x-6 justify-center md:justify-end"
                :class="{'hidden':!navbarOpen,'flex':navbarOpen}">
                <div class="p-2 enfa">
                    <a href="{% url 'change_lang' %}?lang=en&next=/en/{{request.path|slice:'4:'}}">EN</a> / 
                    <a href="{% url 'change_lang' %}?lang=fa&next=/fa/{{request.path|slice:'4:'}}">FA</a>
                </div>
                {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:dashboard' %}"
                    class="group py-1 px-3 flex text-[#3c3c3b] font-semibold text-xs rounded-md hover:text-[#005797] transition ease-in-out duration-500 mb-5 md:mb-0">
                    <div class="mr-3 text-[#005797] ">
                        <i data-feather="log-in"></i>
                    </div>
                    <h1 class="group-hover:text-[#005797] text-[#3c3c3b]">{% blocktranslate with name=request.user.username %}My Account {{name}} {% endblocktranslate %} </h1>
                </a>
                <a href="{% url 'accounts:logout' %}"
                    class="group py-1 px-3 flex text-[#3c3c3b] font-semibold text-xs rounded-md hover:text-[#005797] transition ease-in-out duration-500 mb-5 md:mb-0">
                    <h1 class="group-hover:text-[#005797] text-[#3c3c3b]">{% translate 'Sign Out' %}</h1>
                </a>
                {% else %}
                <a href="{% url 'accounts:login' %}"
                    class="group py-1 px-3 flex text-[#3c3c3b] font-semibold text-xs rounded-md hover:text-[#005797] transition ease-in-out duration-500 mb-5 md:mb-0">
                    <div class="mr-3 text-[#005797] ">
                        <i data-feather="log-in"></i>
                    </div>
                    <h1 class="group-hover:text-[#005797] text-[#3c3c3b]">{% translate 'Sign in | Register' %}</h1>
                </a>
                    
                {% endif %}
                <a href="#"
                    class="group px-3 py-1 flex text-[#3c3c3b] font-semibold text-xs rounded-md transition ease-linear duration-200">
                    <div class="mr-3 text-[#005797] ">
                        <i data-feather="calendar"></i>
                    </div>
                    <h1 class="group-hover:text-[#005797] text-[#3c3c3b]">{% translate 'Bookings' %}</h1>
                </a>
            </div>
            <nav class="text-[#3c3c3b] flex-wrap lg:flex items-center px-4 navbar" x-data="{navbarOpen:false,subnavbarOpen:false }">
                <div class="flex items-center mb-10 lg:mb-0">
                    <a href="{% url 'website:index' %}">
                    <img class="logo" src="{% static 'images/logo.jpg' %}" alt="Logo"></a>
                    <a href="{% url 'website:index' %}">

                    <h1 class="text-xl text-[#3c3c3b] font-bold">{% translate 'arakooshan' %}</h1></a>
                    
                    <button
                        class="lg:hidden w-10 h-10 ml-auto flex items-center justify-center border border-[#005797] text-[#005797] rounded-md"
                        @click="navbarOpen = !navbarOpen">
                        <i data-feather="menu"></i>
                    </button>

                </div>
                <ul class="font-bold lg:flex flex-col lg:flex-row lg:items-center lg:space-x-8 xl:space-x-14 justify-end main-menu-ul"
                    :class="{'hidden':!navbarOpen,'flex':navbarOpen}">
                    <li class="font-semibold text-[#3c3c3b] hover:text-gray-400 transition ease-in-out duration-300 mb-5 lg:mb-0 main-menu-ul-home">
                        <a href="{% url 'website:index' %}">{% translate 'Home' %}</a>
                    </li>
                    <li class="font-semibold text-[#252525] hover:text-[#252525] transition ease-in-out duration-100 mb-5 lg:mb-0">
                        <div class="dropdown inline-block relative">
                            <a class="py-2 px-2 rounded inline-flex items-center" href={% url 'course:categories' %}>
                                <span>{% translate 'Courses' %}</span>
                            </a>
                            <ul class="dropdown-content absolute hidden pt-1">
                                {% for category in categories %}
                                <li class="dropdown">
                                    <a class="bg-[#f1f1f1] hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" href="{% url 'course:single' category.id %}">{{category.name}}</a>
                                    <ul class="dropdown-content dropdown-content-second absolute hidden text-gray-700 pl-5 -mt-10 ">
                                        <li><a class="bg-[#f1f1f1] hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" href="{% url 'course:single' category.id %}">Courses</a>
                                        <li><a class="bg-[#f1f1f1] hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" href="#">References & Training material</a>
                                        <li><a class="bg-[#f1f1f1] hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" href="#">Assesments</a>
                                        <li><a class="bg-[#f1f1f1] hover:bg-gray-400 py-2 px-4 block whitespace-no-wrap" href="#">Enrolment</a>
                                    </ul>
                                </li>
                                
                                {% endfor %}
                            </ul>
                        </div>
                        

                    </li>
                    <li
                        class="font-semibold text-[#3c3c3b] hover:text-gray-400 transition ease-in-out duration-300 mb-5 lg:mb-0">
                        <a href="#">{% translate 'Consultancy' %}</a>
                    </li>
                    <li
                        class="font-semibold text-[#3c3c3b] hover:text-gray-400 transition ease-in-out duration-300 mb-5 lg:mb-0">
                        <a href="{% url 'blog:index' %}">{% translate 'Articles' %}</a>
                    </li>
                    <li
                        class="font-semibold text-[#3c3c3b] hover:text-gray-400 transition ease-in-out duration-300 mb-5 lg:mb-0">
                        <a href="{% url 'website:about' %}">{% translate 'About us' %}</a>
                    </li>
                    <li
                        class="font-semibold text-[#3c3c3b] hover:text-gray-400 transition ease-in-out duration-300 mb-5 lg:mb-0">
                        <a href="{% url 'website:contact' %}">{% translate 'Contact' %}</a>
                    </li>
                </ul>


            </nav>
        </div> <!-- container.// -->
    </section>
    <!-- navbar section //end -->


    {% block content %}

    {% endblock %}


    <footer class="bg-[#444444] py-16 text-[#f1f1f1]">

        <div class="container max-w-screen-xl mx-auto px-4">
            <div class="flex flex-col lg:flex-row lg:justify-between">

                <div class="text-center lg:text-left space-y-7 mb-10 lg:mb-0">
                    <h4 class="font-semibold text-gray-200 text-lg md:text-2xl">Contacts</h4>

                    <a href="#" class="block font-light text-gray-100 text-sm md:text-lg hover:text-gray-800 transition ease-in-out duration-300">
                        <div class="flex mr-4 text-gray-100">
                            <i data-feather="phone"></i>
                            <div class="ml-4">
                                +021 223 456 54 
                            </div>
                        </div>  
                    </a>

                    <a href="#" class="block font-light text-gray-100 text-sm md:text-lg hover:text-gray-800 transition ease-in-out duration-300">
                        <div class="flex mr-4 text-gray-100">
                            <i data-feather="phone"></i>
                            <div class="ml-4">
                                +021 545 643 21  
                            </div>
                        </div>
                    </a>

                    <a href="#" class="block font-light text-gray-400 text-sm md:text-lg hover:text-gray-800 transition ease-in-out duration-300">
                        <div class="flex mr-4 text-gray-100">
                            <i data-feather="mail"></i>
                            <div class="ml-4">
                                info@farakooshan.com  
                            </div>
                        </div>
                    </a>
                </div>

                <div class="text-center lg:text-left space-y-7 mb-10 lg:mb-0">
                    <h4 class="font-semibold text-gray-200 text-lg md:text-2xl">Stay Connected</h4>

                    <a href="#" class="block font-light text-gray-400 text-sm md:text-lg hover:text-gray-800 transition ease-in-out duration-300">
                        <div class="flex mr-4 text-gray-100">
                            <i data-feather="instagram"></i>
                            <div class="ml-4">
                                farakooshan 
                            </div>
                        </div>
                    </a>

                    <a href="#" class="block font-light text-gray-400 text-sm md:text-lg hover:text-gray-800 transition ease-in-out duration-300">
                        <div class="flex mr-4 text-gray-100">
                            <i data-feather="facebook"></i>
                            <div class="ml-4">
                                farakooshan.com  
                            </div>
                        </div>    
                    </a>

                    <a href="#" class="block font-light text-gray-400 text-sm md:text-lg hover:text-gray-800 transition ease-in-out duration-300">
                        <div class="flex mr-4 text-gray-100">
                            <i data-feather="twitter"></i>
                            <div class="ml-4">
                                fara.kooshan  
                            </div>
                        </div>    
                    </a>

                  
                </div>

                <div class="text-center lg:text-left space-y-7 mb-10 lg:mb-0">
                    
            </div>
            
        </div> <!-- container.// -->
        <div class="text-center justify-center text-gray-100 mt-10">
            <small>© Copyright 2024 Farakooshan </small>
        </div>
    </footer>

    <script>
        feather.replace()
    </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
</body>

</html>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="bg-[#f1f1f1]">
    <div class="flex px-10">   
        <h1 class="text-3xl font-bold m-2">{% translate 'Articles' %}</h1>
        <div class="ml-auto mt-3 h-20">
            <form action="#" class="w-full flex">
                <input class="blog-search rounded-e-md h-10" type="text" placeholder=" Search Courses" name="search">
                <button class="blog-search-button bg-[#005797] p-3 text-white rounded-r-md h-10">
                    <i class="fa fa-search"></i>
                </button>
            </form>
        </div>
    </div> 
    <div class="grid lg:grid-cols-4 lg:px-10 pb-4">
        <div class="articles lg:col-span-3 rounded-md">
            <div class="grid gap-5">
                {% for post in posts %}
                <div class="article bg-white m-auto justify-center rounded-md flex">
                    <div class="px-3 pb-4 article-contents w-full">
                        <a href="{% url 'blog:single' post.id %}"><h1 class="text-xl font-bold mt-2">{{post.title}}</h1></a>
                        <p class="mt-2 text-sm text-[#f1f1f1] invisible md:visible">{{post.content|truncatechars:100|safe}}</p>
                        <div class="flex article-date-auther w-full">
                            <div class="flex article-author">
                                <div class="text-black mr-1"><i data-feather="user" class="w-4"></i></div>
                                <h3 class="text-xs font-semibold">{{post.author.get_full_name}}</h3>
                            </div>
                            <div class="flex article-date invisible md:visible">
                                <div class="text-black ml-auto"><i data-feather="calendar" class="w-4"></i></div> 
                                <h3 class="text-xs text-[#f1f1f1]">{{post.published_date|date:"D d M Y"}}</h3>  
                            </div>
                            <button class="px-3 py-1 font-semibold border border-[#005797] rounded-md ml-auto hover:bg-[#005797] hover:text-white article-readmore">Read more</button>
                        </div>
                    </div>
                    <img src="{{post.image.url}}" class="article_image rounded-md"/>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="sidebar col-span-1 py-6 px-4">
            <div>
                <h1 class="bg-[#005797] text-white justify-center p-4 mb-4 rounded-md text-center font-bold ">Popular Posts</h1>
                <div class="flex bg-white rounded-md mb-2">
                    <img src="{% static 'images/geology.jpg' %}" alt="image" class="rounded-l-md w-2/5 mr-2">
                    <div class="grid grid-rows-2">
                        <h3 class="text-sm font-bold">Title of post</h3>
                        <h4 class="text-gray-400 text-xs">21 November, 2023</h4>
                    </div>
                </div>

                <div class="flex bg-white rounded-md mb-2">
                    <img src="{% static 'images/geology.jpg' %}" alt="image" class="rounded-l-md w-2/5 mr-2">
                    <div class="grid grid-rows-2">
                        <h3 class="text-sm font-bold">Title of post</h3>
                        <h4 class="text-gray-400 text-xs">21 November, 2023</h4>
                    </div>
                </div>
                
                <div class="flex bg-white rounded-md mb-2">
                    <img src="{% static 'images/geology.jpg' %}" alt="image" class="rounded-l-md w-2/5 mr-2">
                    <div class="grid grid-rows-2">
                        <h3 class="text-sm font-bold">Title of post</h3>
                        <h4 class="text-gray-400 text-xs">21 November, 2023</h4>
                    </div>
                </div>
            </div>
            
        </div>
    </div>

</div>

{% endblock %}

templates/category/category-home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}


<div class="flex flex-col md:flex-row justify-between space-x-20 text-white hero-courses px-24 bg-[#444444]">
    <div class="text-center lg:text-left mt-12 ">
        <h1 class="font-semibold text-white text-3xl md:text-6xl leading-normal mb-6 category-home-farsi">{% translate 'Course Directory' %}</h1>
        <p class="font-light text-md md:text-lg leading-normal mb-12 category-home-farsi">
            {% blocktranslate %} As Oil and Gas Training Providers, we develop and deliver oil and gas training at our locations in London and Aberdeen, United Kingdom; Dubai, United Arab Emirates, Kuala Lumpur, Malaysia and Houston, Texas, United States. But we can also deliver training courses at our clients location based on request.
            All our training courses can be delivered at a basic, intermediate or advanced level, depending on the attending delegates or organisational requirements. {% endblocktranslate %}
        </p>
        <button class="mb-12 px-6 py-4 bg-[#005797] hover:bg-white hover:text-[#005797] font-semibold text-white text-lg rounded-xl hover:bg-[#005797] transition ease-in-out duration-500 category-home-farsi-button">
        {% translate 'View course directory' %}
        </button>
    </div>
    
</div>


<section class="bg-[#f1f1f1]">
    <div class="grid md:grid-cols-3 px-11 py-10 gap-10 text-[#f1f1f1]">
        {% for category in categories %}
        <a href="{% url 'course:single' category.id %}" class="col-span-1 bg-white p-10 relative hover:bg-[#005797] hover:text-white">
            <h3 class="text-xl font-semibold">{{category.name}}</h3>
            <p class="text-xs mt-3">{{category.content|safe}}</p>
            <br />
            <h4 class="absolute bottom-0 left-0 text-gray-400 ml-5 mb-5 mt-6"> {{category.course_set.count}} {% translate 'courses available' %}</h4>
            <div class="absolute bottom-0 right-0 w-12 py-4 flex justify-center bg-[#005797] text-white">
                <i data-feather="chevron-right"></i>
            </div>
            <div class="overlay absolute top-0 bottom-0 left-0 right-0"></div>
        </a>
        {% endfor %}

    </div>
</section>


{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<h1>{% translate 'Contact' %}</h1>

{% endblock %}